<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="color-scheme" content="light">
    <title>{{ $merchant?->name ?? 'Merchant sign in' }} · Meter</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    @fonts
</head>
<body class="min-h-screen bg-[#f6f7f9] font-sans text-slate-900 antialiased">
@if (!$merchant)
    <main class="grid min-h-screen lg:grid-cols-2">
        <section class="relative flex flex-col justify-between overflow-hidden bg-[#102f28] p-8 text-white sm:p-16">
            <a href="{{ route('dashboard.index') }}" class="flex items-center gap-3 text-2xl font-semibold tracking-tight"><span class="grid size-10 place-items-center rounded-xl bg-emerald-400 text-[#102f28]">m</span> meter<span class="text-emerald-400">.</span></a>
            <div class="my-16 max-w-lg">
                <p class="mb-6 text-xs font-semibold tracking-[0.2em] text-emerald-300 uppercase">Your merchant workspace</p>
                <h1 class="text-4xl leading-tight font-semibold tracking-tight sm:text-5xl">Every unit.<br>Every customer.<br><span class="text-emerald-300">A clearer picture.</span></h1>
                <p class="mt-6 max-w-sm text-base leading-7 text-emerald-100/70">See how your customers use your product, understand overage revenue, and spot accounts that need attention.</p>
                <div class="mt-10 flex items-end gap-3" aria-hidden="true">@foreach ([24, 40, 32, 56, 48, 72, 64, 88, 80, 104, 96, 124] as $height)<span class="w-6 rounded-t bg-emerald-300/40" style="height: {{ $height }}px"></span>@endforeach</div>
            </div>
            <p class="text-xs text-emerald-100/50">Usage insights. Built around your business.</p>
        </section>
        <section class="flex items-center justify-center px-6 py-16 sm:px-12">
            <div class="w-full max-w-sm">
                <span class="mb-6 inline-flex rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1 text-xs font-medium text-emerald-800">Merchant dashboard</span>
                <h2 class="text-3xl font-semibold tracking-tight">Welcome back</h2>
                <p class="mt-3 text-sm leading-6 text-slate-500">Enter your merchant API token to open your workspace.</p>
                <form method="POST" action="{{ route('dashboard.session.store') }}" class="mt-8 space-y-5">
                    @csrf
                    <div><label for="token" class="mb-2 block text-sm font-medium">Merchant token</label><input id="token" name="token" type="password" required minlength="32" maxlength="256" autocomplete="off" spellcheck="false" placeholder="Paste your merchant token" @error('token') aria-invalid="true" aria-describedby="token-error" @enderror class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm outline-none focus:border-emerald-600 focus:ring-4 focus:ring-emerald-600/10">@error('token')<p id="token-error" role="alert" class="mt-2 text-sm text-red-700">{{ $message }}</p>@enderror</div>
                    <button class="w-full cursor-pointer rounded-xl bg-emerald-800 px-4 py-3 text-sm font-semibold text-white transition hover:bg-emerald-900 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-emerald-800">Open dashboard <span aria-hidden="true" class="ml-2">→</span></button>
                </form>
                <p class="mt-6 text-xs leading-5 text-slate-500">Use the same token as your merchant API. Contact your administrator if you need a token.</p>
            </div>
        </section>
    </main>
@else
    <aside class="fixed inset-y-0 left-0 hidden w-60 flex-col border-r border-slate-200 bg-white px-5 py-8 lg:flex">
        <a href="{{ route('dashboard.index') }}" class="flex items-center gap-3 px-3 text-2xl font-semibold tracking-tight"><span class="grid size-9 place-items-center rounded-xl bg-emerald-800 text-white">m</span> meter<span class="-ml-3 text-emerald-600">.</span></a>
        <p class="mt-12 mb-3 px-3 text-[10px] font-semibold tracking-[0.18em] text-slate-400 uppercase">Workspace</p>
        <nav aria-label="Dashboard sections" class="space-y-2 text-sm">
            <a href="#overview" class="flex items-center gap-3 rounded-xl bg-emerald-50 px-3 py-3 font-semibold text-emerald-900"><span aria-hidden="true">▦</span> Overview</a>
            <a href="#customers" class="flex items-center gap-3 rounded-xl px-3 py-3 text-slate-500 hover:bg-slate-50"><span aria-hidden="true">◎</span> Top customers</a>
            <a href="#revenue" class="flex items-center gap-3 rounded-xl px-3 py-3 text-slate-500 hover:bg-slate-50"><span aria-hidden="true">↗</span> Revenue outlook</a>
            <a href="#attention" class="flex items-center gap-3 rounded-xl px-3 py-3 text-slate-500 hover:bg-slate-50"><span aria-hidden="true">◷</span> Churn risk</a>
        </nav>
        <div class="mt-auto rounded-xl border border-slate-200 p-4"><p class="text-xs font-medium text-slate-400">Connected workspace</p><p class="mt-2 truncate text-sm font-semibold" title="{{ $merchant->name }}">{{ $merchant->name }}</p><form method="POST" action="{{ route('dashboard.session.destroy') }}" class="mt-4">@csrf @method('DELETE')<button class="cursor-pointer text-xs font-medium text-slate-500 hover:text-red-700">Sign out →</button></form></div>
    </aside>
    <div class="lg:ml-60">
        <header class="flex min-h-20 flex-wrap items-center justify-between gap-3 border-b border-slate-200 bg-white px-5 py-4 sm:px-10"><div class="flex items-center gap-2 text-sm"><span class="text-slate-400">Workspace</span><span class="text-slate-300">/</span><span class="font-medium">Overview</span></div><div class="flex items-center gap-3"><span class="max-w-44 truncate text-xs text-slate-500">{{ $merchant->name }}</span><span class="grid size-8 place-items-center rounded-full bg-emerald-100 text-xs font-semibold text-emerald-900">{{ mb_strtoupper(mb_substr($merchant->name, 0, 1)) }}</span><form method="POST" action="{{ route('dashboard.session.destroy') }}" class="lg:hidden">@csrf @method('DELETE')<button class="text-xs text-slate-500">Sign out</button></form></div></header>
        <main id="overview" class="mx-auto max-w-7xl space-y-7 px-5 py-8 sm:px-10 sm:py-10">
            <div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-xs font-medium text-emerald-700">Your business, at a glance</p><h1 class="mt-2 text-3xl font-semibold tracking-tight">Merchant overview</h1><p class="mt-2 text-sm text-slate-500">A little clarity for every decision ahead.</p></div><div class="flex gap-2"><span class="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-medium">{{ $asOf->format('F Y') }} <span class="ml-2 text-slate-400">UTC</span></span><a href="{{ route('dashboard.index') }}" class="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-medium hover:bg-slate-50" aria-label="Refresh dashboard">↻ Refresh</a></div></div>
            <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
                <section class="rounded-2xl border border-slate-200 bg-white p-6"><div class="flex items-center justify-between"><h2 class="text-sm text-slate-500">Usage this month</h2><span class="rounded-lg bg-emerald-50 px-2 py-1 text-emerald-700" aria-hidden="true">↗</span></div><p class="mt-4 text-3xl font-semibold tracking-tight">{{ number_format($usageTotal) }} <span class="text-sm font-normal text-slate-400">units</span></p><p class="mt-3 text-xs text-slate-400">{{ $asOf->startOfMonth()->format('M j') }} – {{ $asOf->format('M j') }} · aggregated usage</p></section>
                <section class="rounded-2xl border border-slate-200 bg-white p-6"><div class="flex items-center justify-between"><h2 class="text-sm text-slate-500">Top customer usage</h2><span class="rounded-lg bg-blue-50 px-2 py-1 text-blue-700" aria-hidden="true">◎</span></div><p class="mt-4 text-3xl font-semibold tracking-tight">{{ number_format($dashboard['top_customers']->first()['usage_units'] ?? 0) }} <span class="text-sm font-normal text-slate-400">units</span></p><p class="mt-3 truncate text-xs text-slate-400">{{ $dashboard['top_customers']->first()['name'] ?? 'No customer usage yet' }}</p></section>
                <section class="rounded-2xl border border-slate-200 bg-white p-6"><div class="flex items-center justify-between"><h2 class="text-sm text-slate-500">Customers at risk</h2><span class="rounded-lg bg-amber-50 px-2 py-1 text-amber-700" aria-hidden="true">◷</span></div><p class="mt-4 text-3xl font-semibold tracking-tight">{{ $dashboard['churn_risk_customers']->count() }}{{ $dashboard['churn_risk_customers']->count() === $dashboard['churn_risk_limit'] ? '+' : '' }} <span class="text-sm font-normal text-slate-400">accounts</span></p><p class="mt-3 text-xs text-slate-400">More than 50% usage decline · completed months</p></section>
            </div>
            <div class="grid gap-6 xl:grid-cols-3">
                <section class="min-w-0 rounded-2xl border border-slate-200 bg-white p-6 xl:col-span-2"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="font-semibold">Usage activity</h2><p class="mt-1 text-xs text-slate-400">Daily units, month to date</p></div><button id="export-usage" type="button" class="cursor-pointer rounded-lg border border-slate-200 px-3 py-2 text-xs font-medium hover:bg-slate-50">↓ Export CSV</button></div><div class="mt-7 flex items-center gap-2 text-xs text-slate-500"><span class="size-2 rounded-full bg-emerald-600"></span> {{ $asOf->format('F') }} <span class="ml-auto">Peak: {{ number_format($chartMaximum === 1 && $usageTotal === 0 ? 0 : $chartMaximum) }} units</span></div><svg viewBox="0 0 760 220" role="img" aria-label="Daily aggregated usage for {{ $asOf->format('F Y') }}" class="mt-4 w-full"><defs><linearGradient id="usage-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#059669" stop-opacity="0.15"/><stop offset="100%" stop-color="#059669" stop-opacity="0"/></linearGradient></defs>@foreach ([30, 70, 110, 150, 190] as $y)<line x1="20" x2="740" y1="{{ $y }}" y2="{{ $y }}" stroke="#eef2f6" stroke-dasharray="4 4"/>@endforeach<polygon points="20,190 {{ $chartPoints }} {{ $days->count() > 1 ? 740 : 20 }},190" fill="url(#usage-fill)"/><polyline points="{{ $chartPoints }}" fill="none" stroke="#059669" stroke-width="3" stroke-linejoin="round" stroke-linecap="round"/>@foreach ($days as $day)<circle cx="{{ round(20 + $loop->index * 720 / max(1, $days->count() - 1), 2) }}" cy="{{ round(190 - $day['units'] / $chartMaximum * 160, 2) }}" r="4" fill="#059669"><title>{{ $day['label'] }}: {{ number_format($day['units']) }} units</title></circle>@endforeach</svg><div class="flex justify-between text-[11px] text-slate-400"><span>{{ $days->first()['label'] }}</span><span>{{ $days->last()['label'] }}</span></div><details class="mt-4 text-xs text-slate-500"><summary class="cursor-pointer">View daily values</summary><div class="mt-3 max-h-44 overflow-auto">@foreach ($days as $day)<p class="flex justify-between border-b border-slate-100 py-2"><span>{{ $day['label'] }}</span><span>{{ number_format($day['units']) }} units</span></p>@endforeach</div></details></section>
                <section id="revenue" class="scroll-mt-6 rounded-2xl bg-[#102f28] p-6 text-white"><span class="inline-flex rounded-full bg-white/10 px-3 py-1 text-[10px] font-medium tracking-wide text-emerald-200 uppercase">Revenue outlook</span><h2 class="mt-6 text-lg font-medium">Projected overage</h2><p class="mt-2 text-xs leading-5 text-emerald-100/60">Estimated end-of-cycle overage from usage so far.</p><div class="my-7 space-y-4">@forelse ($dashboard['projected_overage_revenue'] as $currency => $minor)<div><p class="text-xs text-emerald-200/70">{{ $currency }}</p><p class="mt-1 text-4xl font-semibold tracking-tight">{{ number_format(intdiv($minor, 100)) }}.{{ str_pad((string) ($minor % 100), 2, '0', STR_PAD_LEFT) }}</p></div>@empty<p class="text-xl">No active subscriptions</p>@endforelse</div><div class="border-t border-white/15 pt-5 text-xs leading-6 text-emerald-100/60">Projections follow each subscription’s billing cycle and pricing segments. Actual charges may vary.</div><a href="#customers" class="mt-6 inline-flex items-center gap-3 text-xs font-medium text-emerald-200">Explore customer usage <span aria-hidden="true">→</span></a></section>
            </div>
            <section id="customers" class="scroll-mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div class="flex items-center justify-between gap-4 p-6"><div><h2 class="font-semibold">Your top customers</h2><p class="mt-1 text-xs text-slate-400">The five highest-usage accounts this month</p></div><span class="rounded-full bg-slate-100 px-3 py-1 text-xs text-slate-500">{{ $asOf->format('M Y') }}</span></div><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="border-y border-slate-100 bg-slate-50/70 text-[10px] tracking-wide text-slate-400 uppercase"><tr><th scope="col" class="px-6 py-3 font-medium">Customer</th><th scope="col" class="px-6 py-3 font-medium">Usage units</th><th scope="col" class="px-6 py-3 font-medium">Share of month</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($dashboard['top_customers'] as $customer)<tr><td class="px-6 py-4"><div class="flex items-center gap-3"><span class="grid size-9 shrink-0 place-items-center rounded-xl bg-slate-100 text-xs font-medium text-slate-500">{{ mb_strtoupper(mb_substr($customer['name'], 0, 2)) }}</span><div><p class="font-medium">{{ $customer['name'] }}</p><p class="mt-1 text-[11px] text-slate-400">Account #{{ $customer['customer_id'] }}</p></div></div></td><td class="px-6 py-4 font-medium tabular-nums">{{ number_format($customer['usage_units']) }}</td><td class="min-w-44 px-6 py-4"><div class="flex items-center gap-3"><div class="h-1.5 w-24 overflow-hidden rounded-full bg-emerald-50"><div class="h-full rounded-full bg-emerald-600" style="width: {{ min(100, round($customer['usage_units'] / max(1, $usageTotal) * 100, 1)) }}%"></div></div><span class="text-xs text-slate-500">{{ round($customer['usage_units'] / max(1, $usageTotal) * 100, 1) }}%</span></div></td></tr>@empty<tr><td colspan="3" class="px-6 py-12 text-center text-sm text-slate-400">No aggregated customer usage this month. New activity appears after aggregation runs.</td></tr>@endforelse</tbody></table></div></section>
            <section id="attention" class="scroll-mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div class="flex flex-wrap items-center justify-between gap-3 p-6"><div><h2 class="font-semibold">Accounts that need attention</h2><p class="mt-1 text-xs text-slate-400">{{ \Carbon\CarbonImmutable::parse($dashboard['churn_windows']['previous_start'])->format('F') }} compared with {{ \Carbon\CarbonImmutable::parse($dashboard['churn_windows']['recent_start'])->format('F') }} · more than 50% usage decline</p></div><span class="rounded-full bg-amber-50 px-3 py-1 text-xs font-medium text-amber-800">Churn risk</span></div><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="border-y border-slate-100 bg-slate-50/70 text-[10px] tracking-wide text-slate-400 uppercase"><tr><th scope="col" class="px-6 py-3 font-medium">Customer</th><th scope="col" class="px-6 py-3 font-medium">Previous month</th><th scope="col" class="px-6 py-3 font-medium">Recent month</th><th scope="col" class="px-6 py-3 font-medium">Change</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($dashboard['churn_risk_customers'] as $customer)<tr><td class="px-6 py-4 font-medium">{{ $customer['name'] }}</td><td class="px-6 py-4 text-slate-500 tabular-nums">{{ number_format($customer['previous_usage_units']) }}</td><td class="px-6 py-4 text-slate-500 tabular-nums">{{ number_format($customer['recent_usage_units']) }}</td><td class="px-6 py-4"><span class="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-medium text-amber-800">↓ {{ round((1 - $customer['recent_usage_units'] / $customer['previous_usage_units']) * 100, 1) }}%</span></td></tr>@empty<tr><td colspan="4" class="px-6 py-10 text-center"><p class="text-sm font-medium text-emerald-800">No accounts flagged</p><p class="mt-2 text-xs text-slate-400">No qualifying usage declines across the two completed months.</p></td></tr>@endforelse</tbody></table></div>@if ($dashboard['churn_risk_customers']->count() === $dashboard['churn_risk_limit'])<p class="px-6 py-3 text-xs text-slate-400">Showing the first {{ $dashboard['churn_risk_limit'] }} flagged accounts.</p>@endif</section>
            <footer class="flex flex-wrap justify-between gap-2 pb-4 text-[11px] text-slate-400"><p>Updated {{ $asOf->format('M j, Y · H:i') }} UTC · Usage updates after aggregation</p><p>Meter · Merchant workspace</p></footer>
        </main>
    </div>
    <script type="application/json" id="usage-data">{!! \Illuminate\Support\Js::encode($days->values()) !!}</script>
@endif
</body>
</html>
